# Generated by Django 5.2.11 on 2026-02-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_name',
            new_name='name',
        ),
    ]
